name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v6
        with:
          flutter-version: 3.10.6

      - name: Get dependencies
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
